[package]
name = "tez"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.96"
clap = { version = "4.5.30", features = ["derive"] }
crossterm = "0.28.1"
derive_more = { version = "2.0.1", features = ["from"] }
ratatui = "0.29.0"
thiserror = "2.0.11"
